development:
  access_key_id: your_access_key
  secret_access_key: secret_access_key
  bucket: bucket-dev

test:
  access_key_id: your_access_key
  secret_access_key: secret_access_key
  bucket: bucket-qa

production:
  access_key_id: your_access_key
  secret_access_key: secret_access_key
  bucket: bucket-prod  